---
title: "Nicardipine vs. Clevidipine"
output:
  html_document:
    code_folding: hide
    fig_caption: yes
    toc: yes
    toc_float: yes
  html_notebook:
    code_folding: hide
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(results='asis')

library(readxl)
library(tidyverse)
library(stringr)
library(MESS)
library(tableone)
library(themebg)

sbp <- read_excel("../data/raw/sbp.xlsx") %>%
    mutate(group = if_else(Group == "N", "Nicardipine", "Clevidipine"),
           goal = if_else(Diagnosis == 1, 180, 150),
           diagnosis = if_else(Diagnosis == 1, "Acute Ischemic Stroke", "Intracerebral Hemorrhage")) %>%
    select(patient = `Patient number`,
           group,
           diagnosis,
           admit = `Admit Time`,
           med.time = Time,
           sbp = SBP,
           goal) %>%
    arrange(patient, med.time) %>%
    filter(med.time >= admit) %>%
    group_by(patient) %>%
    mutate(duration = as.numeric(difftime(med.time, first(med.time), units = "hours")),
           interval = as.numeric(difftime(lead(med.time), med.time, units = "hours")),
           interval = coalesce(interval, 0),
           at.goal = sbp <= goal)

drip_start <- read_excel("../data/raw/bp_drip_start.xlsx") %>%
    select(patient = `Patient number`,
           sbp_admit = `Admit SBP`,
           sbp_drip = `Drip StartSBP`) %>%
    left_join(sbp[c("patient", "med.time", "sbp")], by = c("patient", "sbp_drip" = "sbp")) %>%
    arrange(patient, med.time) %>%
    distinct(patient, .keep_all = TRUE) %>%
    rename(drip.datetime = med.time)

sbp_drip <- left_join(sbp, drip_start[c("patient", "drip.datetime")], by = "patient") %>%
    filter(med.time >= drip.datetime) %>%
    mutate(duration = as.numeric(difftime(med.time, first(med.time), units = "hours")),
           interval = as.numeric(difftime(lead(med.time), med.time, units = "hours")),
           interval = coalesce(interval, 0),
           at.goal = sbp <= goal)

sbp.auc <- sbp %>%
    filter(duration <= 24) %>%
    group_by(patient) %>%
    summarize(cum.duration = last(duration),
              sbp.first = first(sbp),
              sbp.last = last(sbp),
              perc.change.sbp = (sbp.last - sbp.first) / sbp.first,
              sbp.min = min(sbp),
              auc.24h = auc(duration, sbp),
              sbp.mean.weighted = auc.24h / cum.duration)

sbp_drip_auc <- sbp_drip %>%
    filter(duration <= 24) %>%
    group_by(patient) %>%
    summarize(cum.duration = last(duration),
              sbp.first = first(sbp),
              sbp.last = last(sbp),
              perc.change.sbp = (sbp.last - sbp.first) / sbp.first,
              sbp.min = min(sbp),
              auc.24h = auc(duration, sbp),
              sbp.mean.weighted = auc.24h / cum.duration)

sbp.min <- sbp %>%
    inner_join(sbp.auc, by = "patient") %>%
    filter(sbp == sbp.min) %>%
    arrange(patient, duration) %>%
    group_by(patient) %>%
    summarize(sbp.min.time = first(duration))
    
sbp_drip_min <- sbp_drip %>%
    inner_join(sbp.auc, by = "patient") %>%
    filter(sbp == sbp.min) %>%
    arrange(patient, duration) %>%
    group_by(patient) %>%
    summarize(sbp.min.time = first(duration))

sbp.change <- sbp %>%
    mutate(diff2 = abs(2 - duration),
           diff6 = abs(6 - duration)) %>%
    group_by(patient) %>%
    filter(duration == 0 | (diff2 == min(diff2) & diff2 <= 1) | (diff6 == min(diff6) & diff6 <= 1)) %>%
    mutate(change = sbp - first(sbp)) %>%
    filter(duration > 0) %>%
    mutate(period = if_else(diff2 <= 1, "change.2hr", if_else(diff6 <= 1, "change.6hr", NA_character_))) %>%
    group_by(patient, period) %>%
    summarize(change = first(change)) %>%
    spread(period, change)

sbp_drip_change <- sbp_drip %>%
    mutate(diff2 = abs(2 - duration),
           diff6 = abs(6 - duration)) %>%
    group_by(patient) %>%
    filter(duration == 0 | (diff2 == min(diff2) & diff2 <= 1) | (diff6 == min(diff6) & diff6 <= 1)) %>%
    mutate(change = sbp - first(sbp)) %>%
    filter(duration > 0) %>%
    mutate(period = if_else(diff2 <= 1, "change.2hr", if_else(diff6 <= 1, "change.6hr", NA_character_))) %>%
    group_by(patient, period) %>%
    summarize(change = first(change)) %>%
    spread(period, change)

sbp.goal <- sbp %>%
    filter(duration <= 24,
           at.goal == TRUE) %>%
    group_by(patient) %>%
    summarize(time.at.goal = sum(interval))

sbp_drip_goal <- sbp_drip %>%
    filter(duration <= 24,
           at.goal == TRUE) %>%
    group_by(patient) %>%
    summarize(time.at.goal = sum(interval))

data.bp <- sbp %>%
    ungroup() %>%
    distinct(patient, group, diagnosis) %>%
    left_join(sbp.auc, by = "patient") %>%
    left_join(sbp.min, by = "patient") %>%
    left_join(sbp.goal, by = "patient") %>%
    mutate(perc.time.at.goal = time.at.goal / cum.duration) %>%
    left_join(sbp.change, by = "patient")

data_drip_bp <- sbp_drip %>%
    ungroup() %>%
    distinct(patient, group, diagnosis) %>%
    left_join(sbp_drip_auc, by = "patient") %>%
    left_join(sbp_drip_min, by = "patient") %>%
    left_join(sbp_drip_goal, by = "patient") %>%
    mutate(perc.time.at.goal = time.at.goal / cum.duration) %>%
    left_join(sbp_drip_change, by = "patient")

mean.bp <- data.bp %>%
    group_by(group, diagnosis) %>%
    summarize(auc.24h.mean = mean(auc.24h, na.rm = TRUE),
              auc.24h.sd = sd(auc.24h, na.rm = TRUE),
              auc.24h.se = auc.24h.sd / sqrt(length(auc.24h)),
              change.2hr.mean = mean(change.2hr, na.rm = TRUE),
              change.2hr.sd = sd(change.2hr, na.rm = TRUE),
              change.2hr.se = change.2hr.sd / sqrt(length(change.2hr)),
              change.6hr.mean = mean(change.6hr, na.rm = TRUE),
              change.6hr.sd = sd(change.6hr, na.rm = TRUE),
              change.6hr.se = change.6hr.sd / sqrt(length(change.6hr)))

mean_drip_bp <- data_drip_bp %>%
    group_by(group, diagnosis) %>%
    summarize(auc.24h.mean = mean(auc.24h, na.rm = TRUE),
              auc.24h.sd = sd(auc.24h, na.rm = TRUE),
              auc.24h.se = auc.24h.sd / sqrt(length(auc.24h)),
              change.2hr.mean = mean(change.2hr, na.rm = TRUE),
              change.2hr.sd = sd(change.2hr, na.rm = TRUE),
              change.2hr.se = change.2hr.sd / sqrt(length(change.2hr)),
              change.6hr.mean = mean(change.6hr, na.rm = TRUE),
              change.6hr.sd = sd(change.6hr, na.rm = TRUE),
              change.6hr.se = change.6hr.sd / sqrt(length(change.6hr)))


# wilcox.test(auc.24h ~ group, data = data.bp, subset = data.bp$diagnosis == "stroke")

# tests <- data.bp %>%
#     slice_rows("diagnosis") %>%
#     by_slice(partial(wilcox.test, auc.24h ~ group))
# tests$.out
```


## Primary Outcome

#### All Patients

```{r primary_all, results='asis'}
df <- sbp %>%
    filter(sbp <= goal) %>%
    arrange(patient, duration) %>%
    distinct(patient, .keep_all = TRUE) %>%
    select(patient, group, diagnosis, `Time from Admit to Goal SBP (hours)` = duration)

vars <- names(df)[-c(1:3)]
tbl <- CreateTableOne(vars, "group", df)
ptbl <- print(tbl, printToggle = FALSE)
knitr::kable(ptbl[, 1:3], caption = "All Patients")
```

#### Stroke

```{r stroke_primary, results='asis'}
tbl <- CreateTableOne(vars, "group", df[df$diagnosis == "Acute Ischemic Stroke", ])
ptbl <- print(tbl, printToggle = FALSE)
knitr::kable(ptbl[, 1:3], caption = "Stroke")
```

#### ICH

```{r ich_primary, results='asis'}
tbl <- CreateTableOne(vars, "group", df[df$diagnosis == "Intracerebral Hemorrhage", ])
ptbl <- print(tbl, printToggle = FALSE)
knitr::kable(ptbl[, 1:3], caption = "ICH")
```

## Secondary Outcomes

### Drip Initiation

```{r results='asis'}
df <- sbp_drip %>%
    filter(sbp <= goal) %>%
    arrange(patient, duration) %>%
    distinct(patient, .keep_all = TRUE) %>%
    select(patient, group, diagnosis, `Time from Drip Initiation to Goal SBP (hours)` = duration)

vars <- names(df)[-c(1:3)]
tbl <- CreateTableOne(vars, "group", df)
ptbl <- print(tbl, printToggle = FALSE)
knitr::kable(ptbl[, 1:3], caption = "All Patients")
```

#### Stroke

```{r results='asis'}
tbl <- CreateTableOne(vars, "group", df[df$diagnosis == "Acute Ischemic Stroke", ])
ptbl <- print(tbl, printToggle = FALSE)
knitr::kable(ptbl[, 1:3], caption = "Stroke")
```

#### ICH

```{r results='asis'}
tbl <- CreateTableOne(vars, "group", df[df$diagnosis == "Intracerebral Hemorrhage", ])
ptbl <- print(tbl, printToggle = FALSE)
knitr::kable(ptbl[, 1:3], caption = "ICH")
```

### Summary Statistics

#### All Patients

**Note:** Data within the first 24 hours from time of admission

```{r sbp_all, results='asis'}
df <- data.bp %>%
    select(patient, group, diagnosis,
           `First SBP` = sbp.first,
           `Mean SBP (time-weighted)` = sbp.mean.weighted,
           `Final SBP` = sbp.last,
           `Percent Change in SBP` = perc.change.sbp,
           `Percent Time Below SBP Goal` = perc.time.at.goal,
           `Minimum SBP` = sbp.min,
           `Time to Minimum SBP (hours)` = sbp.min.time,
           `24-Hour SBP AUC` = auc.24h,
           `SBP Change at 2-Hours` = change.2hr,
           `SBP Change at 6-Hours` = change.6hr)

vars <- names(df)[-c(1:3)]
tbl <- CreateTableOne(vars, "group", df)
ptbl <- print(tbl, printToggle = FALSE)
knitr::kable(ptbl[, 1:3], caption = "All Patients")
```

#### Stroke
```{r stroke_mean, results='asis'}
# vars <- c("auc.24h", "change.2hr", "change.6hr")
tbl <- CreateTableOne(vars, "group", df[df$diagnosis == "Acute Ischemic Stroke", ])
ptbl <- print(tbl, printToggle = FALSE)
knitr::kable(ptbl[, 1:3], caption = "Stroke")
```

#### ICH
```{r ich_mean, results='asis'}
tbl <- CreateTableOne(vars, "group", df[df$diagnosis == "Intracerebral Hemorrhage", ])
ptbl <- print(tbl, printToggle = FALSE)
knitr::kable(ptbl[, 1:3], caption = "ICH")
```

### Summary from Drip Initiation

#### All Patients

**Note:** Data within the first 24 hours from time of drip initation

```{r results='asis'}
df <- data_drip_bp %>%
    select(patient, group, diagnosis,
           `First SBP` = sbp.first,
           `Mean SBP (time-weighted)` = sbp.mean.weighted,
           `Final SBP` = sbp.last,
           `Percent Change in SBP` = perc.change.sbp,
           `Percent Time Below SBP Goal` = perc.time.at.goal,
           `Minimum SBP` = sbp.min,
           `Time to Minimum SBP (hours)` = sbp.min.time,
           `24-Hour SBP AUC` = auc.24h,
           `SBP Change at 2-Hours` = change.2hr,
           `SBP Change at 6-Hours` = change.6hr)

vars <- names(df)[-c(1:3)]
tbl <- CreateTableOne(vars, "group", df)
ptbl <- print(tbl, printToggle = FALSE)
knitr::kable(ptbl[, 1:3], caption = "All Patients")
```

#### Stroke
```{r results='asis'}
# vars <- c("auc.24h", "change.2hr", "change.6hr")
tbl <- CreateTableOne(vars, "group", df[df$diagnosis == "Acute Ischemic Stroke", ])
ptbl <- print(tbl, printToggle = FALSE)
knitr::kable(ptbl[, 1:3], caption = "Stroke")
```
#### ICH
```{r results='asis'}
tbl <- CreateTableOne(vars, "group", df[df$diagnosis == "Intracerebral Hemorrhage", ])
ptbl <- print(tbl, printToggle = FALSE)
knitr::kable(ptbl[, 1:3], caption = "ICH")
```

## Figures

```{r, eval=FALSE}
sbp %>%
    filter(duration < 25) %>%
    ggplot(aes(x = duration, y = sbp)) +
    geom_point(aes(color = group), alpha = 0.7, size = 0.7) +
    geom_smooth(aes(linetype = group), color = "black") +
    ggtitle("Figure 1. Change in systolic blood pressure") +
    xlab("Time from admission (hours)") +
    ylab("Systolic blood pressure (mmHg)") +
    facet_grid(. ~ diagnosis) +
    scale_x_continuous(breaks = seq(0, 24, 6)) +
    scale_linetype(name = "Trend") +
    # scale_shape(name = "Values", solid = FALSE) +
    scale_color_brewer(palette = "Paired", guide = guide_legend(title = "Values")) +
    theme_bw() +
    coord_cartesian(ylim = c(50, 250))
```

```{r, message=FALSE, fig.cap="Change in systolic blood pressure from drip initiation"}
sbp_hourly <- sbp_drip %>%
    mutate(hour = floor(duration)) %>%
    distinct(patient, hour, .keep_all = TRUE)

sbp_drip %>%
    filter(duration < 25) %>%
    ggplot() +
    geom_point(data = sbp_hourly, aes(x = duration, y = sbp, shape = group), alpha = 0.4, size = 0.8) +
    geom_smooth(aes(x = duration, y = sbp, linetype = group), color = "black") +
    facet_grid(. ~ diagnosis) +
    scale_x_continuous("Time from drip initiation (hours)", breaks = seq(0, 24, 6)) +
    scale_y_continuous("Systolic blood pressure (mmHg)", breaks = seq(0, 300, 25)) +
    scale_linetype(name = "SBP Trend") +
    scale_shape_manual(name = "SBP Values", values = c(2, 3)) +
    theme_bg() +
    theme(legend.title = element_text(color = "grey35")) +
    coord_cartesian(ylim = c(75, 225))
```

```{r, eval=FALSE}
sbp_drip %>%
    filter(duration < 25) %>%
    mutate(diff_goal = sbp - goal) %>%
    ggplot(aes(x = duration, y = diff_goal)) +
    geom_smooth(aes(linetype = group), color = "black") +
    ggtitle("Figure 3. Systolic blood pressure difference from goal") +
    xlab("Time from drip initiation (hours)") +
    ylab("Systolic blood pressure difference (mmHg)") +
    facet_grid(. ~ diagnosis) +
    scale_x_continuous(breaks = seq(0, 24, 6)) +
    scale_linetype(name = "Group") +
    theme_bw() 
```


## Distribution

```{r}
ggplot(sbp, aes(x = sbp)) +
    geom_histogram(binwidth = 5) 
```

```{r}
qqnorm(sbp$sbp)
```

